export const userData = [
    {
      name: "Jan",
      "Active User": 4000,
    },
    {
      name: "Feb",
      "Active User": 3000,
    }, 
    {
      name: "March",
      "Active User": 5000,
    }, 
    {
      name: "April",
      "Active User": 4000,
    }, 
    {
      name: "May",
      "Active User": 3000,
    }, 
    {
      name: "June",
      "Active User": 2000,
    }, 
    {
      name: "July",
      "Active User": 4000,
    }, 
    {
      name: "August",
      "Active User": 3000,
    }, 
    {
      name: "Sep",
      "Active User": 4000,
    }, 
    {
      name: "Oct",
      "Active User": 1000,
    }, 
    {
      name: "Nov",
      "Active User": 4000,
    }, 
    {
      name: "Dec",
      "Active User": 3000,
    },

  ];

  export const userRows = [
    
    {  
      id: 1  ,
        username: 'Jon Snow',
          avatar: "https://www.pexels.com/photo/man-in-black-suit-jacket-5308640/",
         email: "jon@gmail.com",
         status: "active",
         transaction: "$120.00",
   }, 
{  
  id: 2,
    username: 'Jon Snow',
      avatar: "https://www.pexels.com/photo/man-in-black-suit-jacket-5308640/",
     email: "jon@gmail.com",
     status: "active",
     transaction: "$120.00",
}, 
{ 
  id: 3,
username: 'Jon Snow',
 avatar: "https://www.pexels.com/photo/man-in-black-suit-jacket-5308640/",
 email: "jon@gmail.com",
 status: "active",
 transaction: "$120.00",
}, 
{
   id: 4,
username: 'Jon Snow',
 avatar:  "https://www.pexels.com/photo/man-in-black-suit-jacket-5308640/",
 email: "jon@gmail.com",
 status: "active",
 transaction: "$120.00",
}, 
{ 
  id: 5,
username: 'Jon Snow',
 avatar: "https://www.pexels.com/photo/man-in-black-suit-jacket-5308640/",
 email: "jon@gmail.com",
 status: "active",
 transaction: "$120.00",
}, 
{ id: 6,
username: 'Jon Snow',
 avatar:  "https://www.pexels.com/photo/man-in-black-suit-jacket-5308640/",
 email: "jon@gmail.com",
 status: "active",
 transaction: "$120.00",
}, 
{ id: 7,
username: 'Jon Snow',
 avatar:  "https://www.pexels.com/photo/man-in-black-suit-jacket-5308640/",
 email: "jon@gmail.com",
 status: "active",
 transaction: "$120.00",
}, 
{ id: 8,
username: 'Jon Snow',
 avatar:  "https://www.pexels.com/photo/man-in-black-suit-jacket-5308640/",
 email: "jon@gmail.com",
 status: "active",
 transaction: "$120.00",
}, 
{ id: 9,
username: 'Jon Snow',
 avatar: "https://www.pexels.com/photo/man-in-black-suit-jacket-5308640/",
 email: "jon@gmail.com",
 status: "active",
 transaction: "$120.00",
}, 
{ id: 10,
username: 'Jon Snow',
 avatar: "https://www.pexels.com/photo/man-in-black-suit-jacket-5308640/",
 email: "jon@gmail.com",
 status: "active",
 transaction: "$120.00",
}, 

];